### ISSUE TITLE
Please include either %{datetime} or %{date} in the pattern

### ISSUE THREAD

**Issue by ZEALi** [ljw1004/fix-camera-date#3]
Since I use the pattern, I surely know about the output format that I really wanted.
But if I use
`FixCameraDate *.* /rename "%{year}%{month}%{day}_%{hour}%{minute}%{second}_%{fn}"`
It'll pop up the error message as titled.

Is that necessary?

**Comment by ljw1004** [comment]
Thanks ZEALi. I honestly have no idea why I even put in that error message in the first place. I've removed it.
